global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:
  - "alerts.yml"


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"



scrape_configs:


  # Prometheus Self Monitoring
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"



  # Spring Boot Application
  - job_name: "springboot-app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "springboot-app:8080"



  # Jenkins Metrics
  # Requires Jenkins Prometheus plugin
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "jenkins:8080"



  # Node Exporter - EC2 Server Monitoring
  - job_name: "node-exporter"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "node-exporter:9100"



  # cAdvisor - Docker Container Monitoring
  - job_name: "cadvisor"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "cadvisor:8080"



  # Alertmanager Monitoring
  - job_name: "alertmanager"
    static_configs:
      - targets:
          - "alertmanager:9093"
