global:
  scrape_interval: 15s
  evaluation_interval: 15s


rule_files:
  - "alerts.yml"


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"


scrape_configs:

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"


  # Spring Boot Application
  - job_name: "springboot-app"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "43.204.220.244:8081"


  # Jenkins Metrics (if Jenkins exporter is running)
  - job_name: "jenkins"
    metrics_path: "/prometheus"
    static_configs:
      - targets:
          - "43.204.220.244:8080"


  # Node Exporter for EC2 server monitoring
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "43.204.220.244:9100"


  # Docker container monitoring (cAdvisor)
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "43.204.220.244:8082"
